# Cloudflare Pages Functions 配置文件
# 用于部署到 Cloudflare Pages

[env.production]
name = "libmark-character-parser"
compatibility_date = "2024-01-01"

# Pages Functions 配置
[[pages_functions]]
# 函数目录
functions_dir = "functions"

# 环境变量（如果需要）
[vars]
ENVIRONMENT = "production"
MAX_FILE_SIZE = "10485760"  # 10MB
CACHE_TTL = "3600"  # 1小时

# 路由配置
[[pages_functions.routes]]
pattern = "/api/*"
function = "api"
